sudo: required
python:
  - "2.7"

install:
  - sudo pip install pygments
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.24.1/hugo_0.24.1_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
  - rm -rf public || exit 0

script:
  - pygmentize -V
  - git submodule update --init --recursive
  - hugo -v

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $gh-token
  keep-history: true
  on:
    branch: master